### ISSUE TITLE
In transifex is old text for lit task

### ISSUE THREAD

**Issue by deevroman** [Zverik/osmstreak#64]
Transifex: City at night looks better when the streets are lit. _Add ''lit=yes'' or ''lit=no'' to few roads, and later watch it get coloured [http://product.itoworld.com/map/69 on this map]._

Repository:  City at night looks better when the streets are lit. Add ''lit=yes'' or ''lit=no'' to few roads.
https://github.com/Zverik/osmstreak/blob/master/tasks/2_lit.yaml

**Comment by Zverik** [comment]
Fixed, thanks.

**Comment by Strubbl** [comment]
This is not fixed yet. When was the last sync to transifex? I still see the old text there

**Comment by Zverik** [comment]
Updated it yesterday. Sorry it took so long.

**Comment by Strubbl** [comment]
Thank you, no problem. I was just confused that this issue is fixed and i couldn't find it on transifex. I thought there is some sync automation between transifex and this repo which is broken, but it is done manually?
